services:
  system-one:
    image: ghcr.io/zulfifazhar/system-one:latest
    container_name: system-one-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./models:/app/models
    restart: unless-stopped
